In [2]:
!pip install pandas
import pandas as pd

Collecting pandas
  Downloading pandas-3.0.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.3-cp313-cp313-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mrafaelbatista/devSourceCode/261_UNIESP_MBA-DADOS_data_mining_inferencia_estatistica/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/mrafaelbatista/devSourceCode/261_UNIESP_MBA-DADOS_data_mining_inferencia_estatistica/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 688.9 kB/s eta 0:00:0000:0100:01
Downloading numpy-2.4.3-cp313-cp313-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 795.6 kB/s eta 0:00:00a 0:00:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.3 pandas-3.0.1

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [5]:
df = pd.read_csv('../datasets/ProuniRelatorioDadosAbertos2020.csv', encoding='latin1', sep=';')

In [6]:
df.head()

,ANO_CONCESSAO_BOLSA,CODIGO_EMEC_IES_BOLSA,NOME_IES_BOLSA,MUNICIPIO,CAMPUS,TIPO_BOLSA,MODALIDADE_ENSINO_BOLSA,NOME_CURSO_BOLSA,NOME_TURNO_CURSO_BOLSA,CPF_BENEFICIARIO,SEXO_BENEFICIARIO,RACA_BENEFICIARIO,DATA_NASCIMENTO,BENEFICIARIO_DEFICIENTE_FISICO,REGIAO_BENEFICIARIO,UF_BENEFICIARIO,MUNICIPIO_BENEFICIARIO
0,2020,322,UNIVERSIDADE PAULISTA,IPATINGA,IPATINGA,INTEGRAL,EAD,PEDAGOGIA,CURSO A DISTÂNCIA,991.XXX.XXX-91,F,Parda,11/08/1973,N,SUDESTE,MG,GOVERNADOR VALADARES
1,2020,163,UNIVERSIDADE ESTÁCIO DE SÁ,FORTALEZA,EAD VIA CORPVS - CE,INTEGRAL,EAD,MARKETING,CURSO A DISTÂNCIA,067.XXX.XXX-01,M,Parda,13/05/1987,N,NORDESTE,CE,FORTALEZA
2,2020,17670,FACULDADE DE QUIXERAMOBIM,QUIXERAMOBIM,FACULDADE DE QUIXERAMOBIM - UNIQ,INTEGRAL,PRESENCIAL,FARMÁCIA,NOTURNO,623.XXX.XXX-27,M,Parda,23/07/2001,N,NORDESTE,CE,MOMBACA
3,2020,203,UNIVERSIDADE SÃO JUDAS TADEU,SAO PAULO,PAULISTA,PARCIAL,PRESENCIAL,DIREITO,MATUTINO,089.XXX.XXX-40,F,Branca,04/04/2003,N,NORDESTE,BA,IBITITA
4,2020,203,UNIVERSIDADE SÃO JUDAS TADEU,SAO PAULO,PAULISTA,INTEGRAL,PRESENCIAL,DIREITO,MATUTINO,173.XXX.XXX-09,F,Branca,07/12/1977,N,SUDESTE,SP,SAO PAULO

In [9]:
df_pb = df[df['UF_BENEFICIARIO'] == 'PB']
df_pb.head()

,ANO_CONCESSAO_BOLSA,CODIGO_EMEC_IES_BOLSA,NOME_IES_BOLSA,MUNICIPIO,CAMPUS,TIPO_BOLSA,MODALIDADE_ENSINO_BOLSA,NOME_CURSO_BOLSA,NOME_TURNO_CURSO_BOLSA,CPF_BENEFICIARIO,SEXO_BENEFICIARIO,RACA_BENEFICIARIO,DATA_NASCIMENTO,BENEFICIARIO_DEFICIENTE_FISICO,REGIAO_BENEFICIARIO,UF_BENEFICIARIO,MUNICIPIO_BENEFICIARIO
342,2020,1491,CENTRO UNIVERSITÁRIO INTERNACIONAL,CAMPINA GRANDE,PAP CAMPINA GRANDE,PARCIAL,EAD,GESTÃO FINANCEIRA,CURSO A DISTÂNCIA,073.XXX.XXX-46,F,Branca,02/01/1988,N,NORDESTE,PB,CAMPINA GRANDE
400,2020,1491,CENTRO UNIVERSITÁRIO INTERNACIONAL,JOAO PESSOA,PAP JOÃO PESSOA 02,PARCIAL,EAD,PSICOPEDAGOGIA,CURSO A DISTÂNCIA,046.XXX.XXX-05,F,Parda,22/04/1983,N,NORDESTE,PB,JOAO PESSOA
428,2020,1491,CENTRO UNIVERSITÁRIO INTERNACIONAL,CAMPINA GRANDE,PAP CAMPINA GRANDE,PARCIAL,EAD,ADMINISTRAÇÃO,CURSO A DISTÂNCIA,496.XXX.XXX-05,F,Parda,31/10/2000,N,NORDESTE,PB,ARARA
495,2020,1491,CENTRO UNIVERSITÁRIO INTERNACIONAL,CAMPINA GRANDE,PAP CAMPINA GRANDE,PARCIAL,EAD,SERVIÇO SOCIAL,CURSO A DISTÂNCIA,063.XXX.XXX-35,F,Preta,31/05/1986,N,NORDESTE,PB,JUAZEIRINHO
870,2020,1680,FACULDADE UNIRB - MOSSORÓ,MOSSORO,UNIRB MOSSORO NOVA SEDE,INTEGRAL,PRESENCIAL,SISTEMAS DE INFORMAÇÃO,NOTURNO,125.XXX.XXX-44,M,Parda,13/12/1999,N,NORDESTE,PB,CATOLE DO ROCHA